/**
 * GitHub Auto-Commit Script
 * Generated by GitHub Auto-Commit Tool
 * 
 * This script runs automatically in GitHub Actions.
 * It modifies files based on the selected modes and commits the changes.
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

// Configuration
const CONFIG = {
  gitUsername: 'github-actions[bot]',
  gitEmail: '41898282+github-actions[bot]@users.noreply.github.com',
  intensity: parseInt(process.env.COMMIT_INTENSITY || '6', 10) || 1,
  customMessage: 'Auto-commit: update contribution streak',
  modes: {
    visitorCounter: true,
    randomCommit: true,
    dailyQuote: true,
    activityStats: true
  }
};

// Fallback Quotes in case API fails
const FALLBACK_QUOTES = [
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { text: "Talk is cheap. Show me the code.", author: "Linus Torvalds" },
  { text: "Programs must be written for people to read, and only secondarily for machines to execute.", author: "Harold Abelson" },
  { text: "Walking on water and developing software from a specification are easy if both are frozen.", author: "Edward V. Berard" },
  { text: "In software, the most beautiful code, the most beautiful functions, and the most beautiful programs are the ones that do their job and then disappear.", author: "Unknown" },
  { text: "Clean code always looks like it was written by someone who cares.", author: "Michael Feathers" },
  { text: "First, solve the problem. Then, write the code.", author: "John Johnson" },
  { text: "Experience is the name everyone gives to their mistakes.", author: "Oscar Wilde" },
  { text: "Simplicity is the soul of efficiency.", author: "Austin Freeman" },
  { text: "Before software can be reusable it first has to be usable.", author: "Ralph Johnson" }
];

// Random messages for the changelog
const CHANGELOG_MESSAGES = [
  "Optimized memory footprint of background runner",
  "Refactored state management hooks for clarity",
  "Fixed race condition in async webhook handler",
  "Updated build chain dependencies",
  "Improved CSS layout responsive breakpoints",
  "Added test coverage for core auth utilities",
  "Cleaned up stale developer console logs",
  "Secured api endpoint input validation constraints",
  "Updated local documentation manifest",
  "Boosted UI render speeds via memoized callbacks"
];

const EMOJIS = ["🚀", "✨", "🐛", "⚡", "🔥", "🎨", "📝", "🛠️", "🔒", "💚"];

// Helper to execute git command
function runGit(command) {
  try {
    return execSync(command, { stdio: 'pipe' }).toString().trim();
  } catch (error) {
    console.error(`Git command failed: ${command}`);
    console.error(error.stderr ? error.stderr.toString() : error.message);
    return null;
  }
}

// Ensure Git is configured
function configureGit() {
  runGit(`git config --global user.name "${CONFIG.gitUsername}"`);
  runGit(`git config --global user.email "${CONFIG.gitEmail}"`);
}

// Fetch a quote from a public API
async function fetchQuote() {
  // Since we cannot use external npm packages like axios, we use native https
  return new Promise((resolve) => {
    const https = require('https');
    https.get('https://dummyjson.com/quotes/random', (res) => {
      let data = '';
      res.on('data', (chunk) => { data += chunk; });
      res.on('end', () => {
        try {
          const parsed = JSON.parse(data);
          if (parsed && parsed.quote && parsed.author) {
            resolve({ text: parsed.quote, author: parsed.author });
          } else {
            resolve(getRandomFallbackQuote());
          }
        } catch (e) {
          resolve(getRandomFallbackQuote());
        }
      });
    }).on('error', () => {
      resolve(getRandomFallbackQuote());
    });
  });
}

function getRandomFallbackQuote() {
  return FALLBACK_QUOTES[Math.floor(Math.random() * FALLBACK_QUOTES.length)];
}

// Core Operations for each Mode
function updateVisitorCounter() {
  const readmePath = path.join(process.cwd(), 'README.md');
  if (!fs.existsSync(readmePath)) {
    fs.writeFileSync(readmePath, '# Repository\n\n<!-- VISITOR_START -->\n### Visitor Counter: 0\n<!-- VISITOR_END -->\n');
  }

  let content = fs.readFileSync(readmePath, 'utf8');
  
  // Find <!-- VISITOR_START -->...<!-- VISITOR_END -->
  const regex = /(<!-- VISITOR_START -->[\s\S]*?Visitor Counter: )(\d+)([\s\S]*?<!-- VISITOR_END -->)/i;
  
  if (regex.test(content)) {
    content = content.replace(regex, (match, prefix, count, suffix) => {
      const nextCount = parseInt(count, 10) + 1;
      return `${prefix}${nextCount}${suffix}`;
    });
  } else {
    // Append it if not present
    content += '\n<!-- VISITOR_START -->\n### Visitor Counter: 1\n<!-- VISITOR_END -->\n';
  }
  
  fs.writeFileSync(readmePath, content);
  console.log('Updated Visitor Counter in README.md');
}

function updateRandomCommit() {
  const changelogPath = path.join(process.cwd(), 'CHANGELOG.md');
  if (!fs.existsSync(changelogPath)) {
    fs.writeFileSync(changelogPath, '# Changelog\n\nAll notable changes to this project will be documented in this file.\n\n');
  }

  const today = new Date().toISOString().split('T')[0];
  const randomEmoji = EMOJIS[Math.floor(Math.random() * EMOJIS.length)];
  const randomMessage = CHANGELOG_MESSAGES[Math.floor(Math.random() * CHANGELOG_MESSAGES.length)];
  
  const entry = `\n## [${today}] - Auto Log\n- ${randomEmoji} ${randomMessage}\n`;
  
  fs.appendFileSync(changelogPath, entry);
  console.log('Appended to CHANGELOG.md');
}

async function updateDailyQuote() {
  const quotesPath = path.join(process.cwd(), 'QUOTES.md');
  if (!fs.existsSync(quotesPath)) {
    fs.writeFileSync(quotesPath, '# Daily Quotes\n\nA collection of motivational quotes updated daily.\n\n');
  }

  const quote = await fetchQuote();
  const today = new Date().toISOString().split('T')[0];
  
  const entry = `\n### Quote of the Day (${today})\n> "${quote.text}"\n> — *${quote.author}*\n`;
  
  fs.appendFileSync(quotesPath, entry);
  console.log('Appended quote to QUOTES.md');
}

function updateActivityStats(commitHash = 'dev-commit') {
  const activityPath = path.join(process.cwd(), 'ACTIVITY.md');
  const today = new Date().toISOString().split('T')[0];
  
  let currentStreak = 1;
  let historyLines = '';
  
  if (fs.existsSync(activityPath)) {
    const content = fs.readFileSync(activityPath, 'utf8');
    
    // Parse current streak
    const streakMatch = content.match(/Current Streak: \*\*(\d+) Days\*\*/i);
    const lastActiveMatch = content.match(/Last Active: \*([0-9-]{10})\*/i);
    
    if (streakMatch && lastActiveMatch) {
      const prevStreak = parseInt(streakMatch[1], 10);
      const lastActiveStr = lastActiveMatch[1];
      
      const lastActiveDate = new Date(lastActiveStr);
      const todayDate = new Date(today);
      const diffTime = Math.abs(todayDate - lastActiveDate);
      const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));
      
      if (diffDays === 1) {
        // Active consecutive day
        currentStreak = prevStreak + 1;
      } else if (diffDays === 0) {
        // Active same day, keep streak
        currentStreak = prevStreak;
      } else {
        // Streak broken
        currentStreak = 1;
      }
    }
    
    // Extract everything below the markdown divider
    const tableHeaderIndex = content.indexOf('| Date |');
    if (tableHeaderIndex !== -1) {
      // Get all existing rows
      const rows = content.substring(tableHeaderIndex).split('\n').slice(2);
      historyLines = rows.filter(r => r.trim().length > 0).slice(0, 15).join('\n'); // Keep last 15 rows
    }
  }
  
  const newRow = `| ${today} | `${commitHash}` | Auto Streak Maintenance | Active 🟢 |`;
  
  const newContent = `# Git Activity Log

Current Streak: **${currentStreak} Days**
Last Active: *${today}*

## Streak Log (Last 15 Records)
| Date | Commit Hash | Action Details | Status |
|------|-------------|----------------|--------|
${newRow}
${historyLines ? historyLines : ''}
`;

  fs.writeFileSync(activityPath, newContent);
  console.log('Updated ACTIVITY.md streak to ' + currentStreak);
}

// Primary execution flow
async function main() {
  console.log('Starting Auto-Commit workflow execution...');
  configureGit();

  const totalCommits = CONFIG.intensity;
  console.log(`Ready to perform ${totalCommits} commits...`);

  for (let i = 0; i < totalCommits; i++) {
    console.log(`\n--- Commit iteration ${i + 1} of ${totalCommits} ---`);
    let changed = false;

    // Run active modes
    if (CONFIG.modes.visitorCounter) {
      updateVisitorCounter();
      changed = true;
    }
    
    if (CONFIG.modes.randomCommit) {
      updateRandomCommit();
      changed = true;
    }
    
    if (CONFIG.modes.dailyQuote) {
      await updateDailyQuote();
      changed = true;
    }

    if (changed) {
      // Stage files
      runGit('git add .');
      
      // Perform local commit
      const subMsg = totalCommits > 1 ? ` (Part ${i + 1}/${totalCommits})` : '';
      const finalMsg = `${CONFIG.customMessage}${subMsg} [skip ci]`;
      
      const commitOutput = runGit(`git commit -m "${finalMsg}"`);
      
      if (commitOutput) {
        // Extract commit hash
        const hashMatch = commitOutput.match(/\[[^ ]+ ([0-9a-f]+)\]/i);
        const hash = hashMatch ? hashMatch[1] : 'unknown';
        
        // Update activity log with real commit hash (only if activity stats mode is enabled)
        if (CONFIG.modes.activityStats) {
          updateActivityStats(hash);
          runGit('git add ACTIVITY.md');
          runGit(`git commit --amend -m "${finalMsg}"`); // Amend the commit to include the updated log
        }
      }
    } else {
      console.log('No file modes enabled. Writing heartbeat to log...');
      const logPath = path.join(process.cwd(), 'heartbeat.log');
      fs.appendFileSync(logPath, `Heartbeat: ${new Date().toISOString()}\n`);
      runGit('git add heartbeat.log');
      runGit(`git commit -m "${CONFIG.customMessage} [skip ci]"`);
    }
    
    // Brief sleep to ensure distinct timestamps
    if (totalCommits > 1) {
      execSync('sleep 1');
    }
  }

  console.log('\nAll local commits completed successfully! Pushing changes...');
}

main().catch(console.error);
